(() => {
  'use strict';
  let peer=null, conn=null, role=null, opponent='', gameType='', cleanup=()=>{};
  const $=id=>document.getElementById(id), stage=()=>$('stage');
  const me=()=>localStorage.getItem('birthdayUser')||'لاعب';
  const other=()=>me()==='حمزة'?'بيان':'حمزة';
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const titles={target:'🎯 اضرب الهدف',memory:'🧠 الذاكرة',xo:'❌⭕ XO',reaction:'⚡ ردة الفعل',numbers:'🔢 ذاكرة الأرقام',simon:'🧠 Simon',word:'🔤 خمن الكلمة',quiz:'🏆 Quiz',wheel:'🎡 عجلة التحدي',boxes:'🎁 صناديق المفاجأة',coin:'🪙 تحدي القرارات',higher:'🎴 أعلى أم أقل؟'};
  const css=`.mvModal{position:fixed;inset:0;z-index:1000;background:#0008;display:grid;place-items:center;padding:18px}.mvBox{width:min(540px,100%);background:#fff;border-radius:30px;padding:28px;text-align:center;color:#111;box-shadow:0 25px 80px #0005}.mvBox h2{color:#111}.mvGrid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:20px 0}.mvBtn{border:2px solid #e4cad6;background:#fff;border-radius:20px;padding:20px;color:#111;font-weight:900;cursor:pointer}.mvBtn:hover{border-color:#b52f64}.mvInput{width:100%;padding:14px;border:2px solid #ddc5d1;border-radius:14px;text-align:center;font-size:1.4rem;letter-spacing:5px;color:#111}.mvCode{font-size:2.4rem;letter-spacing:8px;font-weight:950;color:#b52f64;background:#fff0f6;border-radius:18px;padding:16px;margin:15px 0;user-select:all}.mvStatus{background:#fff0f6;color:#111;border-radius:16px;padding:14px;margin:14px 0;line-height:1.8}.mvPlayers{display:flex;justify-content:center;align-items:center;gap:14px;margin:14px}.mvPlayer{background:#f8edf2;padding:10px 16px;border-radius:16px;font-weight:900;color:#111}.mvVs{color:#b52f64;font-size:1.4rem}.mvScore{display:flex;justify-content:center;gap:12px;flex-wrap:wrap}.mvScore span{background:#fff0f6;padding:10px 15px;border-radius:14px;font-weight:900;color:#111}.mvArena{height:310px;background:#fff0f6;border-radius:22px;position:relative;overflow:hidden}.mvTarget{position:absolute;width:60px;height:60px;border:0;border-radius:50%;background:#b52f64;color:#fff;font-size:1.3rem;cursor:pointer}.mvBoard{display:grid;grid-template-columns:repeat(3,80px);gap:7px;justify-content:center}.mvCell{height:80px;border:0;border-radius:12px;background:#b52f64;color:#fff;font-size:2rem;cursor:pointer}.mvCell:disabled{opacity:.65}.mvAnswers{display:grid;grid-template-columns:1fr 1fr;gap:10px}.mvAnswer{padding:14px;border:2px solid #e1c5d1;background:#fff;border-radius:15px;color:#111;font-weight:900;cursor:pointer}.mvBig{font-size:3rem;font-weight:950;color:#b52f64}.mvFinish{background:linear-gradient(135deg,#fff0f6,#f0e8ff);border-radius:24px;padding:25px;color:#111}.mvFinish h2{color:#b52f64}.mvLine{font-size:30px}.mvMemory{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;max-width:430px;margin:auto}.mvMem{height:70px;border:0;border-radius:13px;background:#b52f64;color:#fff;font-size:1.5rem;cursor:pointer}.mvMem.open{background:#fff0f6;color:#111}.mvReaction{width:90%;height:190px;border:0;border-radius:22px;background:#b52f64;color:#fff;font-size:2rem;font-weight:900;cursor:pointer}.mvReaction.go{background:#32935b}@media(max-width:550px){.mvGrid,.mvAnswers{grid-template-columns:1fr}.mvBoard{grid-template-columns:repeat(3,70px)}.mvCell{height:70px}}`;
  function styles(){if($('mvStyle'))return;const s=document.createElement('style');s.id='mvStyle';s.textContent=css;document.head.appendChild(s)}
  function modal(inner){styles();document.querySelector('#mvModal')?.remove();const m=document.createElement('div');m.id='mvModal';m.className='mvModal';m.innerHTML=`<div class="mvBox">${inner}</div>`;document.body.appendChild(m);return m}
  const close=()=>document.querySelector('#mvModal')?.remove();
  function mode(type){modal(`<h2>${titles[type]||'اللعبة'}</h2><p>مع مين بدك تلعب؟</p><div class="mvGrid"><button class="mvBtn" id="mvPc">🤖<br>مع الكمبيوتر</button><button class="mvBtn" id="mvHuman">❤️<br>مع ${esc(other())}</button></div><button class="btn alt" id="mvBack">رجوع</button>`);$('mvPc').onclick=()=>{close();const b=document.querySelector(`[data-game="${type}"]`);if(!b)return;b.dataset.mvBypass='1';b.click();delete b.dataset.mvBypass};$('mvHuman').onclick=()=>room(type);$('mvBack').onclick=close}
  function room(type){close();destroy();modal(`<h2>❤️ لعب مع ${esc(other())}</h2><p>واحد ينشئ غرفة والثاني يدخل بالكود.</p><div class="mvGrid"><button class="mvBtn" id="mvCreate">🏠<br>إنشاء غرفة</button><button class="mvBtn" id="mvJoin">🔑<br>دخول بكود</button></div><button class="btn alt" id="mvRoomBack">رجوع</button>`);$('mvCreate').onclick=()=>create(type);$('mvJoin').onclick=()=>join(type);$('mvRoomBack').onclick=()=>mode(type)}
  function code(){const c='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='';for(let i=0;i<6;i++)s+=c[Math.floor(Math.random()*c.length)];return s}
  function destroy(){try{conn?.close()}catch(e){}try{peer?.destroy()}catch(e){}peer=null;conn=null;role=null;opponent='';cleanup=()=>{}}
  function send(x){if(conn?.open)conn.send(x)}
  function create(type){const c=code();role='host';gameType=type;modal(`<h2>غرفة اللعب 🎮</h2><p>أرسل الكود إلى ${esc(other())}</p><div class="mvCode">${c}</div><div class="mvStatus" id="mvRoomStatus">جاري إنشاء الغرفة…</div><button class="btn alt" id="mvCancel">إلغاء</button>`);$('mvCancel').onclick=()=>{destroy();close()};try{peer=new Peer('birthday-'+c,{debug:0})}catch(e){$('mvRoomStatus').textContent='تعذر تشغيل الاتصال.';return}peer.on('open',()=>{$('mvRoomStatus').textContent='بانتظار '+other()+'…'});peer.on('connection',c=>{if(conn){c.close();return}conn=c;wire(type)});peer.on('error',e=>{$('mvRoomStatus').textContent='تعذر إنشاء الغرفة: '+(e.type||'error')})}
  function join(type){modal(`<h2>🔑 دخول الغرفة</h2><p>اكتب كود ${esc(other())}</p><input id="mvCode" class="mvInput" maxlength="6" placeholder="ABC123"><div id="mvJoinStatus" class="mvStatus">الكود 6 أحرف/أرقام.</div><button class="btn" id="mvConnect">دخول ❤️</button><button class="btn alt" id="mvJoinBack">رجوع</button>`);$('mvJoinBack').onclick=()=>room(type);$('mvConnect').onclick=()=>{const c=$('mvCode').value.trim().toUpperCase();if(c.length!==6){$('mvJoinStatus').textContent='اكتب الكود كاملًا.';return}role='guest';gameType=type;$('mvJoinStatus').textContent='جاري الاتصال…';try{peer=new Peer({debug:0})}catch(e){return}peer.on('open',()=>{conn=peer.connect('birthday-'+c,{reliable:true});wire(type)});peer.on('error',()=>{$('mvJoinStatus').textContent='تعذر الاتصال. تأكد من الكود وأن الغرفة مفتوحة.'})}}
  function wire(type){conn.on('open',()=>{send({t:'hello',name:me(),type});if(role==='guest')$('mvJoinStatus')&&($('mvJoinStatus').textContent='تم الاتصال…')});conn.on('data',d=>receive(type,d));conn.on('close',()=>disconnect())}
  function receive(type,d){if(!d)return;if(d.t==='hello'){opponent=d.name||other();if(role==='host'){close();start(type,true)}else{close();start(type,false)}}else if(window.__mvReceive)window.__mvReceive(d)}
  function disconnect(){if(!stage()||stage().classList.contains('hide'))return;stage().classList.remove('hide');stage().innerHTML='<div class="mvFinish"><div class="mvBig">💔</div><h2>انقطع الاتصال</h2><p>الجولة انتهت لأن اللاعب الثاني خرج.</p><div class="mvBig">بحبك يا بيان ❤️</div><button class="btn" id="mvDisc">العودة</button></div>';$('mvDisc').onclick=()=>{destroy();stage().classList.add('hide');stage().innerHTML=''}}
  function shell(title,desc){stage().classList.remove('hide');stage().scrollIntoView({behavior:'smooth',block:'center'});stage().innerHTML=`<h2>${title}</h2><p>${desc}</p><div class="mvPlayers"><div class="mvPlayer">${esc(me())}</div><div class="mvVs">VS</div><div class="mvPlayer">${esc(opponent||other())}</div></div><div id="mvStatus" class="mvStatus">جاري تجهيز الجولة…</div><div id="mvGame"></div>`}
  function end(result,extra=''){cleanup();cleanup=()=>{};stage().innerHTML=`<div class="mvFinish"><div class="finishIcon">💖</div><h2>انتهت المواجهة ❤️</h2><div class="result">${result}</div>${extra}<p>النتيجة حلوة… بس الأجمل إنكم لعبتوها سوا.</p><div class="mvBig">بحبك يا بيان ❤️</div><div class="mvLine">❤️ 💗 💕 💖 ✨ ❤️</div><button class="btn" id="mvAgain">جولة ثانية</button><button class="btn alt" id="mvExit">العودة للألعاب</button></div>`;$('mvAgain').onclick=()=>{destroy();mode(gameType)};$('mvExit').onclick=()=>{destroy();stage().classList.add('hide');stage().innerHTML=''}}
  function start(type,isHost){gameType=type;({target:target,memory:memory,xo:xo,reaction:reaction,numbers:numbers,simon:simon,word:word,quiz:quiz,wheel:shared,boxes:shared,coin:coin,higher:higher}[type]||target)(isHost)}
  function target(){shell('🎯 اضرب الهدف','20 ثانية — كل واحد يجمع نقاطه.');$('mvGame').innerHTML='<div class="mvScore"><span>أنت: <b id="a">0</b></span><span>'+esc(opponent||other())+': <b id="b">0</b></span></div><div id="ar" class="mvArena"></div><p>الوقت: <b id="tm">20</b></p>';let s=0,o=0,t=20,done=false,otherDone=false;const ar=$('ar');const spawn=()=>{ar.innerHTML='';const b=document.createElement('button');b.className='mvTarget';b.textContent='❤️';b.style.left=(Math.random()*82+3)+'%';b.style.top=(Math.random()*72+5)+'%';b.onclick=()=>{if(done)return;s++;$('a').textContent=s;send({t:'score',v:s});spawn()};ar.appendChild(b)};function maybe(){if(done&&otherDone){end(s===o?`تعادل <b>${s}-${o}</b> 🤝❤️`:s>o?`أنت فزتِ <b>${s}-${o}</b> 🏆❤️`:`${esc(opponent||other())} فاز <b>${o}-${s}</b> 🏆❤️`)}}window.__mvReceive=d=>{if(d.t==='score'){o=d.v;$('b').textContent=o}if(d.t==='finish'){o=d.v;$('b').textContent=o;otherDone=true;maybe()}};spawn();const timer=setInterval(()=>{t--;$('tm').textContent=t;if(t<=0){clearInterval(timer);done=true;ar.innerHTML='';send({t:'finish',v:s});$('mvStatus').textContent='انتهيت. ننتظر '+esc(opponent||other())+'…';maybe()}},1000);cleanup=()=>{clearInterval(timer);window.__mvReceive=null}}
  function xo(){shell('❌⭕ XO','مواجهة مباشرة — X يبدأ أولًا.');$('mvGame').innerHTML='<div id="xb" class="mvBoard"></div>';const b=$('xb'),c=Array(9).fill(''),my=role==='host'?'X':'O';let turn=role==='host',over=false;const w=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]],win=x=>w.some(a=>a.every(i=>c[i]===x));function render(){c.forEach((v,i)=>{b.children[i].textContent=v;b.children[i].disabled=!!v||!turn||over});$('mvStatus').textContent=over?'انتهت':turn?'دورك':'دور '+esc(opponent||other())}function finish(r){over=true;render();end(r)}window.__mvReceive=d=>{if(d.t==='move'){c[d.i]=d.m;turn=true;render();if(win(d.m))finish(d.m===my?'فزت! 🏆':'خسرت هذه الجولة ❤️');else if(c.every(Boolean))finish('تعادل! 🤝❤️')}};for(let i=0;i<9;i++){const x=document.createElement('button');x.className='mvCell';x.onclick=()=>{if(over||!turn||c[i])return;c[i]=my;turn=false;send({t:'move',i,m:my});render();if(win(my))finish('فزت! 🏆❤️');else if(c.every(Boolean))finish('تعادل! 🤝❤️')};b.appendChild(x)}render();cleanup=()=>{window.__mvReceive=null}}
  function reaction(){shell('⚡ سباق ردة الفعل','الإشارة تظهر للجميع — أول ضغط بعد الإشارة يفوز.');$('mvGame').innerHTML='<button id="rb" class="mvReaction">انتظر…</button>';const b=$('rb');let ready=false,done=false;const delay=1300+Math.random()*2300;const timer=setTimeout(()=>{ready=true;b.classList.add('go');b.textContent='اضغط الآن!';send({t:'go'})},delay);window.__mvReceive=d=>{if(d.t==='go'){ready=true;b.classList.add('go');b.textContent='اضغط الآن!'}};b.onclick=()=>{if(done)return;done=true;clearTimeout(timer);if(!ready){send({t:'false'});end('ضغطت قبل الإشارة 😄❤️');return}send({t:'press',at:Date.now()});end('ضغطتِ أولًا! ⚡🏆❤️')};cleanup=()=>{clearTimeout(timer);window.__mvReceive=null}}
  function memory(){shell('🧠 الذاكرة','كل واحد يلعب نفس فكرة الذاكرة. أقل محاولات يفوز.');const sy=['❤️','🌸','🎂','💎','⭐','🎀','🦋','🍓'],d=[...sy,...sy].sort(()=>Math.random()-.5);$('mvGame').innerHTML='<div id="mb" class="mvMemory"></div><div class="mvScore"><span>محاولاتك: <b id="mm">0</b></span><span>'+esc(opponent||other())+': <b id="mo">—</b></span></div>';const b=$('mb');let open=[],moves=0,match=0,lock=false;d.forEach((v,i)=>{const x=document.createElement('button');x.className='mvMem';x.textContent='?';x.onclick=()=>{if(lock||x.classList.contains('open'))return;x.textContent=v;x.classList.add('open');open.push(i);if(open.length<2)return;moves++;$('mm').textContent=moves;const[a,z]=open;if(d[a]===d[z]){match++;open=[];if(match===sy.length){send({t:'mem',moves});end('أكملت الذاكرة! 🧠🏆')}}else{lock=true;setTimeout(()=>{[a,z].forEach(k=>{b.children[k].textContent='?';b.children[k].classList.remove('open')});open=[];lock=false},600)}};b.appendChild(x)});window.__mvReceive=d=>{if(d.t==='mem'){$('mo').textContent=d.moves}};cleanup=()=>{window.__mvReceive=null}}
  function quiz(){const q=[['شو التاريخ المميز؟',['5 فبراير','5 مارس','25 فبراير'],0],['مين صاحب عيد الميلاد؟',['حمزة','بيان','الكمبيوتر'],1],['شو أجمل كلمة؟',['سلام','بحبك','موز'],1],['مين كتب الموقع؟',['حمزة','جوجل','سبونج بوب'],0],['شو النتيجة الأهم؟',['النقاط','الفوز','إننا سوا ❤️'],2]];let i=0,s=0,o=0;const render=()=>{const[x,opts,correct]=q[i];shell('🏆 Quiz ضد '+esc(opponent||other()),`السؤال ${i+1} من ${q.length}`);$('mvGame').innerHTML='<div class="mvScore"><span>أنت: '+s+'</span><span>'+esc(opponent||other())+': '+o+'</span></div><h3>'+x+'</h3><div id="qa" class="mvAnswers"></div>';opts.forEach((v,j)=>{const b=document.createElement('button');b.className='mvAnswer';b.textContent=v;b.onclick=()=>{s+=j===correct?1:0;i++;send({t:'qs',s,i});if(i===q.length){send({t:'qend',s});end(`نتيجتك <b>${s}/${q.length}</b> 🏆❤️`,`<p>نتيجة ${esc(opponent||other())}: <b>${o}/${q.length}</b></p>`)}else render()});$('qa').appendChild(b)})};window.__mvReceive=d=>{if(d.t==='qs'){o=d.s;render()}if(d.t==='qend')o=d.s};render();cleanup=()=>{window.__mvReceive=null}}
  function numbers(){shared('🔢 ذاكرة الأرقام','نفس الرقم يظهر للطرفين ثم تختبرون ذاكرتكم.')}
  function simon(){shared('🧠 Simon','في وضع الشخصين، اضغطوا جاهز وابدأوا نفس التحدي على جهاز كل واحد.')}
  function word(){shared('🔤 خمن الكلمة','في وضع الشخصين، اضغطوا جاهز وابدأوا نفس التحدي معًا.')}
  function coin(){shared('🪙 تحدي القرارات','5 قرارات سريعة — بدون أي رهانات.');}
  function higher(){shared('🎴 أعلى أم أقل؟','تحدي مشترك سريع — اضغطوا جاهز وابدأوا الجولة.');}
  function shared(title,desc){shell(title,desc);$('mvGame').innerHTML='<div class="mvStatus">اضغطوا جاهز على الجهازين، وبعدها تبدأ الجولة المشتركة.</div><button id="ready" class="btn">أنا جاهز ❤️</button><div id="ri" class="result">ننتظر الطرفين.</div>';let r=false,o=false;$('ready').onclick=()=>{r=true;$('ready').disabled=true;send({t:'ready'});check()};window.__mvReceive=d=>{if(d.t==='ready'){o=true;check()}};function check(){if(r&&o){$('ri').textContent='الاثنان جاهزان ❤️';setTimeout(()=>end('بدأتوا التحدي سوا — وهذا أحلى فوز ❤️'),500)}}cleanup=()=>{window.__mvReceive=null}}
  function boot(){styles();document.querySelectorAll('[data-game]').forEach(b=>b.addEventListener('click',e=>{if(b.dataset.mvBypass==='1')return;e.preventDefault();e.stopImmediatePropagation();mode(b.dataset.game)},true))}
  document.addEventListener('DOMContentLoaded',boot);
})();